### ISSUE TITLE
Static output in build mode

### ISSUE THREAD

**Issue by nksaraf** [antfu/vite-plugin-inspect#33]
### Clear and concise description of the problem

Really awesome plugin here, we made it part of `solid-start` (`solid-js`'s meta-framework) by default. One part that we missed was getting this same output for the files transformed for SSR. We see the client transformations, but for ex. solid-start does a lot of different transformations based on whether we are building for SSR or Browser. 

### Suggested solution

Would be awesome if there is a toggle to enable the SSR output..

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Yeah, I also want this. Basically, it's allowing the plugin to run in the build pipeline and generate a report in HTML or some other formats instead of serving from the dev server. However, this requires quite some work, to make the client accept data from a static JSON (with some features turned off, etc). I currently don't have enough bandwidth on this, if anyone wants to give it a shot, PR welcome!

**Comment by nksaraf** [comment]
Heyy I think the HTML output during build is awesome! but I think I wanted to communicate something that I screwed up.. 

Basically I was looking for a way to get the `ssr: true` version of the transforms to inspect whats happening in the server-side imports. during dev.

**Comment by antfu** [comment]
I see. I created another issue to track on that https://github.com/antfu/vite-plugin-inspect/issues/34

**Comment by sapphi-red** [comment]
Maybe this issue can be closed by e58f6d6623ff8dc64b73e169a6deba5db89dd2fb?
